<a href="https://colab.research.google.com/github/SoniaMackow/data-science-bootcamp/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello')

Hello


In [ ]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [1]:
import numpy as np
np.__version__

'1.22.4'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
y = np.array([1.3, 3.1, 1.4])
print(y)

[1.3 3.1 1.4]


In [ ]:
y.dtype


dtype('float64')

In [ ]:
z = np.array([[1, 2], [-3, 1]])
print(z)

[[ 1  2]
 [-3  1]]


In [ ]:
z.ndim

2

In [ ]:
z.shape

(2, 2)

In [ ]:
z.dtype

dtype('int64')

In [ ]:
az = np.array([[1, 2, 2], [-3, 2, 1]])
print(z)

[[ 1  2  2]
 [-3  2  1]]


In [ ]:
z.shape

(2, 3)

In [ ]:
a = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 2],
      [4, 2, 1]]]
)
print(a)

[[[4 3 1]
  [3 1 2]]

 [[4 1 2]
  [4 2 1]]]


In [ ]:
a.ndim

3

In [ ]:
a.shape

(2, 2, 3)

# Typy danych



In [ ]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1.0, 2.3, 3.4])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [ ]:
A

array([1., 2., 3.])

In [ ]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [ ]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
A = np.array([1.0, 2.3, 3.4], dtype='int')
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

In [ ]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

# Tworzenie tablic

In [2]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.ones(shape=(5, 5), dtype='int') 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [10]:
list(np.arange(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [13]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [16]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [18]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [19]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Podstawowe operacje na tablicach


In [24]:
A = np.array([1, 2, 3, 4])
B = np.array([3, -1, 2, 4])
print(A)
print(B)

[1 2 3 4]
[ 3 -1  2  4]


In [25]:
A +B

array([4, 1, 5, 8])

In [34]:
np.add(A, B)

array([4, 1, 5, 8])

In [26]:
A - B

array([-2,  3,  1,  0])

In [35]:
np.subtract(A, B)

array([-2,  3,  1,  0])

In [27]:
A * B

array([ 3, -2,  6, 16])

In [36]:
np.multiply(A, B)

array([ 3, -2,  6, 16])

In [28]:
A / B

array([ 0.33333333, -2.        ,  1.5       ,  1.        ])

In [37]:
np.divide(A, B)

array([ 0.33333333, -2.        ,  1.5       ,  1.        ])

In [29]:
A + 3

array([4, 5, 6, 7])

In [30]:
A -5

array([-4, -3, -2, -1])

In [31]:
A * 2

array([2, 4, 6, 8])

In [33]:
A + 3*B

array([10, -1,  9, 16])

In [40]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [44]:
X * Y

array([[6, 0],
       [2, 0]])

In [43]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [46]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [47]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])