<a href="https://colab.research.google.com/github/SoniaMackow/data-science-bootcamp/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('Hello')

Hello


In [6]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [7]:
import numpy as np
np.__version__

'1.22.4'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [11]:
x = np.array([1, 3])
x

array([1, 3])

In [13]:
print(x)

[1 3]


In [14]:
type(x)

numpy.ndarray

In [15]:
x.ndim

1

In [16]:
x.shape

(2,)

In [17]:
x.size

2

In [18]:
x.dtype

dtype('int64')

In [19]:
y = np.array([1.3, 3.1, 1.4])
print(y)

[1.3 3.1 1.4]


In [20]:
y.dtype


dtype('float64')

In [21]:
z = np.array([[1, 2], [-3, 1]])
print(z)

[[ 1  2]
 [-3  1]]


In [22]:
z.ndim

2

In [23]:
z.shape

(2, 2)

In [24]:
z.dtype

dtype('int64')

In [25]:
z = np.array([[1, 2, 2], [-3, 2, 1]])
print(z)

[[ 1  2  2]
 [-3  2  1]]


In [28]:
z.shape

(2, 3)

In [29]:
a = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 2],
      [4, 2, 1]]]
)
print(a)

[[[4 3 1]
  [3 1 2]]

 [[4 1 2]
  [4 2 1]]]


In [31]:
a.ndim

3

In [32]:
a.shape

(2, 2, 3)